spring:
  application:
    name: fiapfood
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: true
  sql:
    init:
      mode: always
  messages:
    encoding: ISO-8859-1
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  servlet:
    context-path: /fiapfood